services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: subscripsync-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123 # In prod, use .env file
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  api:
    build:
      context: .
      dockerfile: SubscripSync.API/Dockerfile
    container_name: subscripsync-api
    depends_on:
      - sqlserver
    ports:
      - "5083:8080" # Map host 5083 to container 8080
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SubscripSyncDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
    restart: on-failure

  client:
    build:
      context: .
      dockerfile: SubscripSync.Client/Dockerfile
    container_name: subscripsync-client
    depends_on:
      - api
    ports:
      - "4200:80" # Map host 4200 to container 80
    restart: always

volumes:
  sqlvolume:
